language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated xctool || (brew uninstall xctool && brew upgrade xctool)

script: xctool -project break-iOS/break/break.xcodeproj -scheme break build -destination "platform=iOS Simulator,name=iPhone 6s"
