language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool

script: xctool -project break-iOS/break/break.xcodeproj -scheme break build
